{
  "config_id": "CFG_BASELINE_0001_B_T009",
  "runtime_target": "windows-native",
  "prior_data_id": "NONE",
  "modules": {
    "M0": {
      "impl_id": "m0_none",
      "params": {}
    },
    "M1": {
      "impl_id": "m1_stub",
      "params": {}
    },
    "M2": {
      "impl_id": "m2_stub2",
      "params": {
        "dummy_thr": 0.579596102969316,
        "boost": 0.000359541949254677
      }
    },
    "M3": {
      "impl_id": "m3_stub",
      "params": {}
    },
    "M4": {
      "impl_id": "m4_stub",
      "params": {
        "split_eps_m": 7.280606234095842
      }
    },
    "M5": {
      "impl_id": "m5_stub",
      "params": {}
    },
    "M6a": {
      "impl_id": "m6a_stub",
      "params": {
        "smooth_lambda": 0.2921145548552495
      }
    },
    "M6b": {
      "impl_id": "m6b_stub",
      "params": {}
    },
    "M6c": {
      "impl_id": "m6c_stub",
      "params": {}
    },
    "M7": {
      "impl_id": "m7_stub",
      "params": {}
    },
    "M8": {
      "impl_id": "m8_stub",
      "params": {}
    },
    "M9": {
      "impl_id": "m9_stub",
      "params": {}
    }
  }
}