drives:
- drive: 2013_05_28_drive_0000_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 2708.141
  intersections_count: 5
  intersections_area_total_m2: 1512.554
  width_median_m: 12.446
  width_p95_m: 24.276
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0003_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 2754.255
  intersections_count: 3
  intersections_area_total_m2: 1298.579
  width_median_m: 13.971
  width_p95_m: 22.465
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0004_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 3769.565
  intersections_count: 6
  intersections_area_total_m2: 2591.488
  width_median_m: 15.118
  width_p95_m: 34.562
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0005_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 2892.55
  intersections_count: 4
  intersections_area_total_m2: 1818.017
  width_median_m: 14.049
  width_p95_m: 29.956
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0006_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 2846.034
  intersections_count: 4
  intersections_area_total_m2: 1585.23
  width_median_m: 13.071
  width_p95_m: 33.592
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0007_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 8120.202
  intersections_count: 1
  intersections_area_total_m2: 447.02
  width_median_m: 12.116
  width_p95_m: 15.582
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0009_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 3898.773
  intersections_count: 2
  intersections_area_total_m2: 521.431
  width_median_m: 12.368
  width_p95_m: 16.881
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
- drive: 2013_05_28_drive_0010_sync
  backend_used: nn
  internal_epsg: 32632
  centerline_total_len_m: 4488.635
  intersections_count: 3
  intersections_area_total_m2: 1185.68
  width_median_m: 14.396
  width_p95_m: 21.45
  road_component_count_after: 1
  centerlines_in_polygon_ratio: 1.0
