KITTI_ROOT: ""
TARGET_EPSG: 32632
ROI_BUFFER_M: 20.0
RASTER_RES_M: 0.20
VOXEL_SIZE_M: 0.05
MAX_FRAMES: 3000
GROUND_BAND_DZ_M: 0.15
MIN_DENSITY: 8
ROAD_ROUGHNESS_MAX_M: 0.05
ROAD_CLOSE_RADIUS_M: 0.6
BG_WIN_RADIUS_M: 3.0
MARKING_AREA_RATIO_MIN: 0.005
MARKING_AREA_RATIO_MAX: 0.04
MARKING_CLOSE_RADIUS_M: 0.6
MARKING_SCORE_TH: -1.0
MARKING_SCORE_PCTL_CHOSEN: -1.0
CROSSWALK_MERGE_RADIUS_M: 1.0
CROSSWALK_W_MIN_M: 2.5
CROSSWALK_W_MAX_M: 8.0
CROSSWALK_L_MIN_M: 3.0
CROSSWALK_L_MAX_M: 20.0
CROSSWALK_AREA_MIN_M2: 10.0
CROSSWALK_AREA_MAX_M2: 200.0
CROSSWALK_MIN_COMPONENTS: 4
TIME_BUDGET_H: 6.0
TRAJ_STRIDE: 5
STRIDE: 1
LIDAR_WORLD_MODE: "fullpose"
OVERWRITE: true
GOLDEN_DRIVES_FILE: "configs/golden_drives.txt"
CROSSWALK_ORI_TOL_DEG: 12.0
CROSSWALK_GAP_MAX_M: 2.2
CROSSWALK_MERGE_BUF_M: 0.6
STRIPE_W_RANGE_M: [0.12, 0.80]
STRIPE_L_RANGE_M: [0.80, 12.0]
STRIPE_AREA_RANGE_M2: [0.15, 20.0]
CLUSTER_MIN_STRIPES: 6
CLUSTER_W_RANGE_M: [2.5, 10.0]
CLUSTER_L_RANGE_M: [3.0, 28.0]
CLUSTER_AREA_RANGE_M2: [10.0, 350.0]
USE_ROAD_MASK: true
