FRAME_START: 250
FRAME_END: 500
STRIDE: 1
TARGET_EPSG: 32632
ROI_BUFFER_M: 30
RANGE_MIN_M: 3.0
RANGE_MAX_M: 45.0
Y_ABS_MAX_M: 20.0
GROUND_RANSAC_ITERS: 200
GROUND_RANSAC_DZ: 0.12
GROUND_NORMAL_DOT_Z_MIN: 0.90
GRID_RES_M: 0.20
MIN_CELL_PTS: 5
OVERWRITE: true
FIT_RANGE_MIN_M: 5.0
FIT_RANGE_MAX_M: 35.0
FIT_Y_ABS_MAX_M: 8.0
FIT_Z_MAX_M: 1.0
CLASSIFY_DZ_M: 0.07
POST_GRID_RES_M: 0.20
POST_MIN_CELL_PTS: 5
POST_RESID_MAX_M: 0.08
EXPORT_NON_GROUND_SAMPLE_RATE: 0.05
