FRAME_START: 280
FRAME_END: 300
STRIDE: 1
TARGET_EPSG: 32632
TRUTH_GPKG: "E:\\Work\\nav-road-pipeline\\crosswalk_truth_utm32.gpkg"
TRUTH_LAYER: "crosswalk_truth"
ROI_PAD_M: 25.0
BG_INNER_M: 10.0
BG_OUTER_M: 35.0
SHIFT_MAX_M: 8.0
SHIFT_STEP_M_COARSE: 0.5
SHIFT_STEP_M_FINE: 0.1
GROUND_ENABLE: true
GROUND_RANSAC_DZ: 0.12
RANGE_MIN_M: 3.0
RANGE_MAX_M: 45.0
INTENSITY_AUTO_SCALE: true
INTENSITY_USABLE_NONZERO_MIN: 0.05
INTENSITY_MIN_DYNAMIC_RANGE: 2000
EXPORT_MAX_POINTS: 3000000
OVERWRITE: true
