FRAME_START: 250
FRAME_END: 500
STRIDE: 1
ROI_BUFFER_M: 30.0
RASTER_RES_M: 0.20
VOXEL_SIZE_M: 0.05
TIME_BUDGET_H: 6
OVERWRITE: true
TARGET_EPSG: 32632
GROUND_BAND_DZ_M: 0.20
MIN_DENSITY: 3
ROAD_ROUGHNESS_MAX_M: 0.20
CLOSE_RADIUS_M: 0.8
OPEN_RADIUS_M: 0.4
MIN_POLY_AREA_M2: 30.0
SIMPLIFY_M: 0.3
PROJ_ENABLE: true
PROJ_KEY_FRAMES: [250, 341, 500]
PROJ_NONROAD_SAMPLE: 20000
PROJ_GROUND_SAMPLE: 80000
