# Fixed defaults for crosswalk map feature merge
INPUT_GPKG_PATH: ""
INPUT_GPKG_EVIDENCE_PATH: ""
DRIVE_ID: ""
IMAGE_CAM: "image_00"
OUTPUT_EPSG: 32632

CLUSTER_DIST_M: 2.5
CLUSTER_IOU_MIN: 0.20
CLUSTER_ORI_DEG: 15
EDGE_DIST_M: 1.0
MERGE_ACROSS_DRIVES: false

FEATURE_SHAPE: "mrr_of_union"
FEATURE_MARGIN_M: 0.30
MIN_FEATURE_AREA_M2: 10.0
MAX_FEATURE_AREA_M2: 350.0

CONF_HIGH_SUPPORT: 5
CONF_MED_SUPPORT: 3

QA_RANDOM_SEED: 20260130
QA_FORCE_INCLUDE: [290]
QA_RANDOM_N: 2

OVERWRITE: true
